Update theme
TaoStats/bittensor-explorer-ui pull request #19
Opened 2023-07-20 15:21 UTC by TopETH

2023-07-21 21:56 UTC, mogmachine requested changes

2023-07-21 22:12 UTC, mogmachine requested changes

2023-07-21 22:12 UTC, mogmachine commented on src/components/SearchInput.tsx
nor border on the search box, button light grey (like the top header buttons on the top right of taostats - caps, light, spaced lettering)

2023-07-21 22:16 UTC, mogmachine requested changes

2023-07-21 22:16 UTC, mogmachine commented on src/theme.tsx
Fonts ..generally using font wight 400 and then 500 for bold, but not 700, ..feels too thick.

Also using 14px for data in tables etc. and 16 or 17px when larger is required.

Finally ... max width on yours is 1400 px ... taostats is 1800 .. (check exact sizes) ..but that makes a difference on high res and larger screens ...so if we could increase please.

2023-07-27 06:36 UTC, mogmachine approved these changes

2023-07-27 06:40 UTC, cute0laf approved these changes

2023-07-27 06:40 UTC, merged