Recycled tao by current owner
TaoStats/bittensor-explorer-ui pull request #304
Opened 2024-02-21 00:49 UTC by TopETH

2024-02-21 14:45 UTC, cuteolaf requested changes

2024-02-21 14:45 UTC, cuteolaf commented on src/components/subnets/SubnetsTable.tsx
> +				render={({ recycledLifetime }) => {
```suggestion
				render={({ raoRecycled24H }) => {
```

2024-02-21 14:45 UTC, cuteolaf commented on src/components/subnets/SubnetsTable.tsx
> +							amount={recycledLifetime}
```suggestion
							amount={raoRecycled24H}
```

2024-02-22 17:31 UTC, mogmachine approved these changes

2024-02-22 21:34 UTC, cuteolaf approved these changes

2024-02-22 21:34 UTC, merged