Schema update on bittensor-subnet
TaoStats/bittensor-explorer-ui pull request #333
Opened 2024-04-05 00:08 UTC by TopETH

2024-04-06 07:04 UTC, mogmachine commented
Please remove decimeal points from final "TOTAL" column. Sorry asked a few times ..easiest to bundle into this PR

2024-04-08 15:00 UTC, cuteolaf requested changes

2024-04-08 15:00 UTC, cuteolaf commented on src/screens/subnet.tsx
> +					: []),
please create a new function for search conditions.

2024-04-08 15:00 UTC, cuteolaf commented on src/utils/number.ts
> +	if (/^\d+\.\d+\.\d+\.\d+$/.test(ip)) return true;
hopefully a better regexp?

2024-04-08 18:02 UTC, merged