Update for validator page
TaoStats/bittensor-explorer-ui pull request #342
Opened 2024-04-09 20:58 UTC by TopETH

2024-04-10 01:47 UTC, cuteolaf commented
- make fonts smaller for boxes
- clip the owner address with '...' when overflow
- hover effect on each box
- when clicked & selected, performance chart of the selected subnet should be shown

2024-04-10 22:00 UTC, cuteolaf commented on src/screens/validator.tsx
> +	border-color: #7aff97 !important;
```suggestion
	border-color: #14dec2 !important;
```

2024-04-12 12:53 UTC, cuteolaf commented on src/components/subnets/ColdkeySubnets.tsx
> +		1024,
we can't remove this constant?

2024-04-12 12:58 UTC, cuteolaf requested changes

2024-04-12 12:59 UTC, TopETH commented on src/screens/validator.tsx
> +			neuronMetagraph.data?.map((meta) => meta.netUid) || [];
Removed.

2024-04-12 13:08 UTC, cuteolaf approved these changes

2024-04-12 13:09 UTC, cuteolaf commented
create a new PR to remove the constants.

2024-04-12 13:09 UTC, merged