Subnet De-registration Chart
TaoStats/bittensor-explorer-ui pull request #365
Opened 2024-05-06 17:08 UTC by TopETH

2024-05-06 22:12 UTC, cuteolaf requested changes

2024-05-06 22:12 UTC, cuteolaf commented on src/components/subnets/NeuronDeregistrationChart.tsx
> +	}, [neuronDeregistrations]);
```suggestion
	const timestamps = useMemo(() => {
		const { data } = neuronDeregistrations;
		if (!data) return [];
		return data.map((x: NeuronDeregistration) => x.timestamp);
	}, [neuronDeregistrations]);
	
	const [minIncentive, maxIncentive] = useMemo(() => {
		const { data } = neuronDeregistrations;
		if (!data) return [0, 0];

		const dat = data.map(({ incentive }) => incentive / 65535);
		return [Math.min(...dat), Math.max(...dat)];
	}, [neuronDeregistrations]);
	
	const [minEmission, maxEmission] = useMemo(() => {
		const { data } = neuronDeregistrations;
		if (!data) return [0, 0];

		const dat = data.map(({ emission }) =>
			rawAmountToDecimal(emission.toString()).toNumber()
		);
		return [Math.min(...dat), Math.max(...dat)];
	}, [neuronDeregistrations]);
	
	const incentives = useMemo(() => {
		const { data } = neuronDeregistrations;
		if (!data) return [];
		return data.map(({ incentive }) => incentive / 65535);
	}, [neuronDeregistrations]);
	
	const emissions = useMemo(() => {
		const { data } = neuronDeregistrations;
		if (!data) return [];
		return data.map(({ emission }) =>rawAmountToDecimal(emission.toString()).toNumber());
	}, [neuronDeregistrations]);
```

2024-05-06 22:12 UTC, cuteolaf commented on src/components/subnets/NeuronDeregistrationChart.tsx
> +					data: incentive,
```suggestion
					data: incentives,
```

2024-05-06 22:12 UTC, cuteolaf commented on src/components/subnets/NeuronDeregistrationChart.tsx
> +					data: emission,
```suggestion
					data: emissions,
```

2024-05-06 22:12 UTC, cuteolaf commented on src/hooks/useNeuronDeregistrations.ts
> +								greaterThan: new Date(from).toISOString().substring(0, 19),
```const from = new Date(now - 7 * 24 * 60 * 60 * 1000).toISOString();```

and

```new Date(from).toISOString()```
?

2024-05-06 22:12 UTC, cuteolaf commented on src/model/subnet.ts
> +	height: bigint;
```suggestion
	height: number;
```

height is of type `number`, not `bigint`

2024-05-06 22:48 UTC, cuteolaf approved these changes

2024-05-07 15:04 UTC, mogmachine approved these changes

2024-05-07 15:04 UTC, merged