Tokenomics page
TaoStats/bittensor-explorer-ui pull request #370
Opened 2024-05-08 14:37 UTC by TopETH

2024-05-08 14:55 UTC, mogmachine approved these changes

2024-05-08 15:24 UTC, cuteolaf requested changes

2024-05-08 15:24 UTC, cuteolaf commented on src/components/tokenomics/HalveningChart.tsx
> +			x: new Date("12 Mar 2021").getTime(),
Is it March or May?

2024-05-08 15:24 UTC, cuteolaf commented on src/components/tokenomics/HalveningChart.tsx
> +				text: "Kusangi Network",
It is **Kusanagi**, not **Kusangi**.

2024-05-08 15:24 UTC, cuteolaf commented on src/components/tokenomics/HalveningChart.tsx
> +			},
repeated several times.
refactor please.

2024-05-08 15:24 UTC, cuteolaf commented on src/components/tokenomics/HalveningChart.tsx
> +			y: 6727871,
Where did you copy this value from?

2024-05-08 15:24 UTC, cuteolaf commented on src/screens/tokenomics.tsx
> +	const secondsPerHalvening = 126000000;
```suggestion
	const secondsPerHalvening = blocksPerHalvening  * 12;
```

2024-05-08 15:24 UTC, cuteolaf commented on src/screens/tokenomics.tsx
> +	];
Does it need to be hard coded?

2024-05-08 15:24 UTC, cuteolaf commented on src/components/tokenomics/TokenomicsChart.tsx
> +	})}% of ${nFormatter(totalSupply.toNumber(), 2)})`;
looks a bit messy, please refactor.

2024-05-08 15:24 UTC, TopETH commented on src/components/tokenomics/HalveningChart.tsx
> +			x: new Date("12 Mar 2021").getTime(),
It's March (in Taostats)

2024-05-08 15:26 UTC, TopETH commented on src/components/tokenomics/HalveningChart.tsx
> +				text: "Kusangi Network",
Fixed

2024-05-08 15:31 UTC, TopETH commented on src/components/tokenomics/HalveningChart.tsx
> +			},
Fixed

2024-05-08 15:33 UTC, cuteolaf commented on src/components/tokenomics/HalveningChart.tsx
> +			x: new Date("12 Mar 2021").getTime(),
Check again.

2024-05-08 15:34 UTC, TopETH commented on src/components/tokenomics/HalveningChart.tsx
> +			y: 6727871,
Fixed

2024-05-08 15:35 UTC, TopETH commented on src/screens/tokenomics.tsx
> +	const secondsPerHalvening = 126000000;
Fixed

2024-05-08 15:37 UTC, TopETH commented on src/components/tokenomics/TokenomicsChart.tsx
> +	})}% of ${nFormatter(totalSupply.toNumber(), 2)})`;
Fixed

2024-05-08 15:51 UTC, TopETH commented on src/components/tokenomics/HalveningChart.tsx
> +			x: new Date("12 Mar 2021").getTime(),
Fixed

2024-05-09 13:26 UTC, cuteolaf approved these changes

2024-05-09 13:27 UTC, merged