Update index page
TaoStats/bittensor-explorer-ui pull request #6
Opened 2023-07-18 20:47 UTC by TopETH

2023-07-18 21:15 UTC, mogmachine requested changes
reformat word "Bittensor" and add in Discord link.

2023-07-18 21:15 UTC, mogmachine commented on src/screens/home.tsx
> +				<div css={subtitleStyle}>Block explorer for BitTensor ecosystem</div>
Don't capitalise BitTensor .. it should be written Bittensor at all times.

2023-07-18 21:15 UTC, mogmachine commented on src/components/Footer.tsx
> +					<a href="#">
Discord link is: https://discord.com/channels/1086368192521318472/1086369375411507290

2023-07-19 08:55 UTC, mogmachine requested changes

2023-07-19 09:01 UTC, cute0laf approved these changes

2023-07-19 09:13 UTC, cute0laf approved these changes

2023-07-19 09:15 UTC, mogmachine approved these changes

2023-07-19 09:15 UTC, merged